package com.jfinal.common.model;

import com.jfinal.common.model.base.BaseBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Book extends BaseBook<Book> {
	public static final Book dao = new Book().dao();
}
