package com.jfinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public M setBid(java.lang.Integer bid) {
		set("bid", bid);
		return (M)this;
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public M setBname(java.lang.String bname) {
		set("bname", bname);
		return (M)this;
	}
	
	public java.lang.String getBname() {
		return getStr("bname");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

}
